version: '2.1'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DATA_ENGINE: "tsm1"
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./data/influxdb:/var/lib/influxdb
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/status"]
      interval: 10s
      timeout: 10s
      retries: 30

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./data/grafana:/var/lib/grafana
      - ./provision/grafana:/etc/grafana/provisioning
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 30

  app:
    container_name: app
    image: app
    build:
      context: .
    command:
      - sh
      - -c
      - ./main history --from 2018-01-01 --to 2019-01-01; /usr/sbin/crond -f -l 8
    restart: "no"
    depends_on:
      influxdb:
        condition: service_healthy
