apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: app
    role: app
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.ini: |-
{{ .Values.config_ini | indent 4 }}
