---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
    role: grafana
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: "app-grafana"
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: app
    role: grafana
  type: NodePort
