---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
    role: influxdb
    chart: {{ template "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: "influxdb"
spec:
  ports:
  - name: http
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: app
    role: influxdb
  type: NodePort
