---

rabbitmq:
  user: tracking_stage
  pass: tracking_stage

tracking:
  db:
    host: tracking-stage-db-1
    user: tracking_test
    pass: tracking_test

pimpay:
  db:
    host: pimpay-stage-db-for-tracking-1
    pass: test_passwd
  apiHost: "http://info-provider-api.tracking-static-swooledb-1.info-provider-api.ppdev.ru"


cronjobs:
  suspend: "true"

