---
api:
  replicas: 1
  resources:
    requests:
      memory: "2000Mi"
      cpu: "1000m"
    limits:
      memory: "4000Mi"
      cpu: "4000m"
  db:
    applicationName: tracking-api

timeouts:
  wait_migrations: 90
  wait_apps: 300

testing:
  jobQueueName: tracker_job
  outputMessageExchangeName: tracker_exchange
  outputMessageRoutingKey: pimpay.common
  notifier_throttling: 1000
  agent_parallelization: 15
  agent_queueName: agent_job
  agent_db_poolsize: 5
  http_maxconnections: 10

core:
  - name: common
    replicas: 1
    cpu_min: 3200m
    mem_min: 2000Mi
    cpu_max: 4000m
    mem_max: 3000Mi
    db_applicationName: tracking-core-common
    db_poolsize: 15
    jobQueueName: tracker_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.common
    notifier_parallelization: 32
    notifier_throttling: 1000
    http_maxConnections: 70
  - name: gdeposylka
    replicas: 1
    cpu_min: 3200m
    mem_min: 2000Mi
    cpu_max: 4000m
    mem_max: 3000Mi
    db_applicationName: tracking-core-gdeposylka
    db_poolsize: 15
    jobQueueName: tracker_gdeposylka_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.gdeposylka
    notifier_parallelization: 32
    notifier_throttling: 1
    http_maxConnections: 70
  - name: loan
    replicas: 1
    cpu_min: 3200m
    mem_min: 2500Mi
    cpu_max: 4000m
    mem_max: 4000Mi
    db_applicationName: tracking-core-loan
    db_poolsize: 8
    jobQueueName: tracker_loan_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.loan
    notifier_parallelization: 16
    notifier_throttling: 1000
    http_maxConnections: 35
  - name: lost
    replicas: 1
    cpu_min: 3200m
    mem_min: 2500Mi
    cpu_max: 4000m
    mem_max: 4000Mi
    db_applicationName: tracking-core-lost
    db_poolsize: 8
    jobQueueName: tracker_lost_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.lost_and_found
    notifier_parallelization: 16
    notifier_throttling: 1000
    http_maxConnections: 35
  - name: inform
    replicas: 1
    cpu_min: 3200m
    mem_min: 2000Mi
    cpu_max: 4000m
    mem_max: 3000Mi
    db_applicationName: tracking-core-inform
    db_poolsize: 8
    jobQueueName: tracker_inform_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.inform
    notifier_parallelization: 16
    notifier_throttling: 1000
    http_maxConnections: 16

agent:
  - name: common
    replicas: 1
    cpu_min: 1700m
    mem_min: 2500Mi
    cpu_max: 4000m
    mem_max: 3500Mi
    db_applicationName: tracking-agent-common
    db_poolsize: 15
    jobQueueName: tracker_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.common
    agent_parallelization: 15
    agent_queueName: agent_job
    http_maxConnections: 128
  - name: loan
    replicas: 1
    cpu_min: 1700m
    mem_min: 2500Mi
    cpu_max: 4000m
    mem_max: 4000Mi
    db_applicationName: tracking-agent-loan
    db_poolsize: 8
    jobQueueName: tracker_loan_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.loan
    agent_parallelization: 8
    agent_queueName: agent_loan_job
    http_maxConnections: 128
  - name: lost
    replicas: 1
    cpu_min: 3200m
    mem_min: 2500Mi
    cpu_max: 4000m
    mem_max: 4000Mi
    db_applicationName: tracking-agent-lost
    db_poolsize: 2
    jobQueueName: tracker_lost_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.lost
    agent_parallelization: 2
    agent_queueName: agent_lost_job
    http_maxConnections: 128


log:
  stdout:
    level: WARN
  logstash:
    host: kibana.ppdev.ru
    port: 7274
    level: DEBUG

rabbitmq:
  hvm: 6144
  host: rabbitmq
  user: tracking_prod
  pass: tracking_prod
  vhost: rabbitmq
  resources:
    requests:
      cpu: 3500m
      memory: 8192Mi
    limits:
      cpu: 4000m
      memory: 14336Mi

tracking:
  db:
    host: tracking-prod-db
    port: 5432
    name: tracking
    user: tracking_prod
    pass: nkUVDppUbz
    poolsize: 5

pimpay:
  db:
    host: dbm
    port: 5432
    name: pp_prod
    user: pp_prod
    pass: Z58DDy9bDeajmtWy
  apiHost: "http://info-provider-api.ppdev.ru"

cronjobs:
  suspend: "false"
  cron_throttle_rate: 10000
  tasks:
  - name: sync_rp_loan_orders
    jobQueueName: tracker_loan_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.loan
    db_poolsize: 8
    schedule: '2 */2 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 1000m
    cpu_max: 4000m
    mem_min: 2000Mi
    mem_max: 4000Mi
    args: 'sync_rp_loan_orders --ttl=3h'
    logstash_queue: loan
  - name: sync_rp_delivered_loan_orders
    jobQueueName: tracker_loan_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.loan
    db_poolsize: 8
    schedule: '35 2 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 1000m
    cpu_max: 4000m
    mem_min: 2000Mi
    mem_max: 4000Mi
    args: 'sync_rp_delivered_loan_orders --ttl=3h'
    logstash_queue: loan
  - name: sync_rp_default
    jobQueueName: tracker_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.common
    db_poolsize: 8
    schedule: '12 */3 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 1000m
    cpu_max: 4000m
    mem_min: 2000Mi
    mem_max: 4000Mi
    args: 'sync_rp_default --ttl=3h'
    logstash_queue: common
  - name: sync_rp_new
    jobQueueName: tracker_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.common
    db_poolsize: 8
    schedule: '22 */1 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 100m
    cpu_max: 500m
    mem_min: 400Mi
    mem_max: 1000Mi
    args: 'sync_rp_new --ttl=2h'
    logstash_queue: common
  - name: sync_rp_delivered_orders
    jobQueueName: tracker_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.common
    db_poolsize: 8
    schedule: '32 22 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 1000m
    cpu_max: 4000m
    mem_min: 2000Mi
    mem_max: 4000Mi
    args: 'sync_rp_delivered_orders --ttl=24h'
    logstash_queue: common
  - name: sync_rp_delivered_prepaid_orders
    jobQueueName: tracker_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.common
    db_poolsize: 8
    schedule: '32 23 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 100m
    cpu_max: 500m
    mem_min: 500Mi
    mem_max: 1000Mi
    args: 'sync_rp_delivered_prepaid_orders --ttl=24h'
    logstash_queue: common
  - name: sync_kaz_post_orders
    jobQueueName: tracker_gdeposylka_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.gdeposylka
    db_poolsize: 8
    schedule: '30 15 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 100m
    cpu_max: 500m
    mem_min: 500Mi
    mem_max: 1000Mi
    args: 'sync_kaz_post_orders --ttl=24h'
    logstash_queue: gdeposylka
  - name: sync_rp_cash_on_delivery
    jobQueueName: tracker_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.common
    db_poolsize: 8
    schedule: '42 1 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 100m
    cpu_max: 500m
    mem_min: 500Mi
    mem_max: 1000Mi
    args: 'sync_rp_cash_on_delivery --returnedOrderAgeInMonths=0 --ttl=24h'
    logstash_queue: common
  - name: sync_rp_lost_orders
    jobQueueName: tracker_lost_job
    outputMessageExchangeName: tracker_exchange
    outputMessageRoutingKey: pimpay.lost
    db_poolsize: 2
    schedule: '30 1 * * *'
    concurrencyPolicy: 'Replace'
    cpu_min: 100m
    cpu_max: 500m
    mem_min: 500Mi
    mem_max: 1000Mi
    args: 'sync_rp_lost_orders --ttl=24h'
    logstash_queue: lost
